import type { AppLocale } from "@/i18n/config";

const copy = {
  en: {
    badge: "Read-only demo",
    dashboard: "Dashboard",
    projects: "Projects",
    signIn: "Sign in",
    createWorkspace: "Create your workspace",
    exit: "Exit demo",
    tour: "Take a quick tour",
    dashboardTitle: "A clear view of every project signal",
    dashboardIntro:
      "Explore a populated SignalBoard workspace. Everything here is fixture data and nothing is written to a database.",
    portfolioTitle: "Built like a real private product",
    portfolioBody:
      "The authenticated product is server-rendered and keeps user-owned data behind Supabase Auth and row-level security. Activity is generated by the database, while localized, timezone-aware deadlines stay consistent across the workspace. This public demo uses read-only fixtures only.",
    directoryTitle: "Demo projects",
    directoryIntro: "Search and inspect realistic project states without creating an account.",
    anyStatus: "Any status",
    anyPriority: "Any priority",
    applyFilters: "Apply filters",
    sortBy: "Sort by",
    noResultsTitle: "No demo projects match",
    noResultsBody: "Adjust or clear the filters to see the full fixture workspace.",
    projectNotFoundTitle: "Demo project not found",
    projectNotFoundBody: "That project is not part of this read-only demo.",
    backToProjects: "Back to demo projects",
    detailEyebrow: "Project detail",
    activity: "Activity history",
    deletedActivityNote:
      "SignalBoard retains database-generated activity after a private project is deleted.",
    tourSteps: [
      {
        title: "Project analytics",
        body: "Status distribution and completion trends turn a busy portfolio into a quick health check.",
      },
      {
        title: "Deadline tracking",
        body: "Overdue work, upcoming dates, and late completions are separated so attention goes to the right place.",
      },
      {
        title: "Immutable activity",
        body: "In the private product, database-generated activity is protected by row-level security. This demo only mirrors that experience with fixtures.",
      },
    ],
    step: (current: number) => `Step ${current} of 3`,
    previous: "Previous",
    next: "Next",
    finish: "Finish",
    closeTour: "Close tour",
  },
  uk: {
    badge: "Демо лише для перегляду",
    dashboard: "Панель",
    projects: "Проєкти",
    signIn: "Увійти",
    createWorkspace: "Створити робочий простір",
    exit: "Вийти з демо",
    tour: "Швидкий огляд",
    dashboardTitle: "Чітка картина кожного сигналу проєкту",
    dashboardIntro:
      "Перегляньте заповнений простір SignalBoard. Тут використано тестові дані й нічого не записується до бази.",
    portfolioTitle: "Побудовано як справжній приватний продукт",
    portfolioBody:
      "Автентифікований продукт рендериться на сервері й захищає дані користувачів через Supabase Auth та RLS. Активність створює база даних, а локалізовані терміни враховують часовий пояс. Це публічне демо використовує лише дані для перегляду.",
    directoryTitle: "Демо-проєкти",
    directoryIntro: "Шукайте й переглядайте реалістичні стани проєктів без реєстрації.",
    anyStatus: "Будь-який статус",
    anyPriority: "Будь-який пріоритет",
    applyFilters: "Застосувати",
    sortBy: "Сортувати",
    noResultsTitle: "Демо-проєктів не знайдено",
    noResultsBody: "Змініть або очистьте фільтри, щоб побачити всі тестові дані.",
    projectNotFoundTitle: "Демо-проєкт не знайдено",
    projectNotFoundBody: "Цього проєкту немає в демо лише для перегляду.",
    backToProjects: "Назад до демо-проєктів",
    detailEyebrow: "Деталі проєкту",
    activity: "Історія активності",
    deletedActivityNote:
      "SignalBoard зберігає створену базою активність після видалення приватного проєкту.",
    tourSteps: [
      {
        title: "Аналітика проєктів",
        body: "Розподіл статусів і динаміка завершень швидко показують стан усього портфеля.",
      },
      {
        title: "Контроль термінів",
        body: "Прострочені роботи, найближчі дати й пізні завершення розділено для правильного фокусу.",
      },
      {
        title: "Незмінна активність",
        body: "У приватному продукті створену базою активність захищає RLS. Демо лише відтворює цей досвід тестовими даними.",
      },
    ],
    step: (current: number) => `Крок ${current} з 3`,
    previous: "Назад",
    next: "Далі",
    finish: "Завершити",
    closeTour: "Закрити огляд",
  },
} as const;

export function getDemoCopy(locale: AppLocale) {
  return copy[locale];
}
